# Current-state judgments are static inspection, not an in-game listening test.
# priority: 1 = first production pass, 2 = next pass, 3 = optional polish.
needs=[]
def n(area,sound,status,priority,detail,hook,candidates=''):
    needs.append(dict(id=f'N{len(needs)+1:02}',area=area,sound=sound,status=status,priority=priority,detail=detail,hook=hook,candidates=candidates.split()))

n('Carrier ambience','Exterior deck machinery bed','Wired; expand',2,'A deck bed exists. Add localized vents, distant machinery and occasional hull settling; vary with carrier load and listener location.','LandCarrier/LandCarrier.gd:2254','S19 S20')
n('Carrier ambience','Bridge and corridor ventilation','Wired; expand',2,'interior_ventilation.ogg already blends room hum and fan. Add distinct bridge, corridor and enclosed-room profiles.','LandCarrier/Commander.gd:960','S16 S17 S18')
n('Carrier ambience','Hangar, vehicle bay and machinery-room ambience','Missing dedicated cues',2,'Use localized fans, electrical transformers, pumps and metal room reflections. Fade at openings instead of one constant everywhere.','LandCarrier/VehicleBayManager.gd','S16 S19 S26')
n('Carrier ambience','Exposed deck wind and sheltered transitions','Partial',1,'Wind already exists in flight/weather and commander mixes. Add dedicated open-deck wind driven by relative wind, height and shelter.','LandCarrier/Commander.gd; Weather/DustFrontVisuals.gd','S21 S22')
n('Carrier ambience','Hull creaks, loose panels and structural settling','Missing dedicated cues',2,'Sparse one-shots while turning, braking and crossing rough ground; avoid a repeating creak loop.','LandCarrier/LandCarrier.gd','S43 S27')
n('Carrier movement','Track-link rolling and clatter','Wired; expand',1,'track_links.ogg follows each tread. Review in-game audibility first; add load/terrain texture and different left/right speed response.','LandCarrier/CarrierTread.gd:641','S31 S32 S34')
n('Carrier movement','Track engagement, braking and skid turns','Missing dedicated cues',1,'Add start clunk, stop settling, tension squeak and hard-turn scrub. A moving loop alone does not communicate these transitions.','LandCarrier/CarrierTread.gd','S33 S35 S43')
n('Carrier movement','Carrier electric drive under load','Partial',2,'Generic deck bed exists; create a distinct load-sensitive electrical drive layer underneath track clatter.','LandCarrier/LandCarrier.gd','S06 S19')
n('Elevators and doors','Deck elevator motor travel','Wired; verify',1,'elevator_moving_mono.wav is wired. Current RuntimeAudio fills a zero-length loop range and elevator update restarts stopped playback. Historical silence is not proof of a current failure.','LandCarrier/CarrierElevator.gd:841; Audio/RuntimeAudio.gd:4','S30 S24 S26')
n('Elevators and doors','Island passenger lift motor','Wired; differentiate',1,'Currently shares the deck-elevator source. Give the smaller lift its own travel, braking and cabin perspective.','LandCarrier/CommanderWalkArea.gd:321','S25 S30')
n('Elevators and doors','Elevator locking pins, release and arrival thump','Missing dedicated cues',1,'Distinct unlock before travel, brake deceleration, then locking clunk only after actual stop/alignment. Different up/down arrivals may need different resonance.','LandCarrier/CarrierElevator.gd; LandCarrier/CommanderWalkArea.gd','S28 S29 S27')
n('Elevators and doors','Elevator covers: lift, slide, close and latch','Partial',1,'Cover movement already raises the shared motor layer. Add separate sliding weight and closing/latch transients.','LandCarrier/CarrierElevator.gd:859','S26 S49 S28')
n('Elevators and doors','Personnel doors: actuator and sealing latch','Partial',2,'door_slide.wav plays on movement/reversal; add final contact/seal only if useful, plus distinct heavy bay-door character.','LandCarrier/CarrierSlidingDoor.gd:21','S28 S49')
n('Deck operations','Catapult engagement, charging, release and reset','Missing dedicated cues',1,'Latch aircraft, tension/charge, launch stroke, release and shuttle return are separate events. Keep launch sound synchronized with the actual shared launch gate.','LandCarrier/Catapult.gd','S27 S46 S47')
n('Deck operations','Landing catch/arrest and release','Missing dedicated cues',1,'A catch transient, deceleration tension and final release should identify successful recovery. Tie to actual catch state rather than nearby flight.','LandCarrier/FlightDeckManager.gd','S27 S28 S35')
n('Deck operations','Recovery robots: drive, arms, clamps and towing','Missing dedicated cues',1,'Electric locomotion, arm servo, wheel clamp, tow strain and clamp release. Stop each layer when that mechanism stops.','LandCarrier/TractorBot.gd','S03 S46 S28')
n('Deck operations','Wing fold/unfold and lock','Missing dedicated cues',2,'Actuator while moving, endpoint latch, and optional obstruction/stall cue. Respect each authored aircraft mechanism.','Aircraft/Visuals; aircraft wing-fold controllers','S46 S28')
n('Deck operations','Rearming, repair and charging services','Suggested extension',3,'Short tool, connector and completion cues where service events are visible; do not create invisible ongoing workshop noise for abstract timers.','LandCarrier/FlightDeckManager.gd','S46 S48 S28')
n('Aircraft propulsion','Distinct electric motor identities','Shared baseline',1,'Eight numbered fixed-wing scenes use airplane_propeller 3.wav; two use airplane_propeller 1.wav. Add separate electrical tone plus aerodynamic layer with per-aircraft profiles.','addons/simplified_flightsim/aircraft_modules/Engine/Engine.gd:18','S01 S02 S03 S07 S14')
n('Aircraft propulsion','Motor start, contactor, acceleration and shutdown','Partial',1,'Startup assets are assigned; EngineSoundStop hook exists but no assignment was found in numbered aircraft scenes. Add contactor click, spool-up, load changes and coast-down.','addons/simplified_flightsim/aircraft_modules/Engine/Engine.gd:18','S01 S05 S47')
n('Aircraft propulsion','Propeller whirr and blade beating','Shared baseline',1,'Provide low/medium/high rotational beds plus blade-load pulse; vary with actual rotation/load and prop layout, not only a pitch shift of one motor loop.','addons/simplified_flightsim/aircraft_modules/Engine/Engine.gd','S08 S09 S10 S11')
n('Aircraft propulsion','Helicopter rotor identity, spool and loaded beating','Wired; differentiate',1,'Aircraft 9–13 and 15 share Helicopter3 slow/medium/fast exterior layers. Add distinct light/utility/heavy rotor balance and spool tails.','Aircraft/Visuals/CounterRotatingRotor.gd:29','S12 S13 S15 S47')
n('Aircraft propulsion','Exterior fly-by and distance perspective','Partial',2,'3D attenuation exists. Review Doppler/distance treatment and directional prop/rotor balance before adding prerecorded fly-bys that could double the engine.','Audio/AudioManager3D.gd; aircraft engine/rotor players','S08 S12')
n('Aircraft interior','Electrical systems and ventilation','Wired; expand',2,'cabin_systems.ogg and per-scene cockpit interiors exist. Distinguish quiet modern, rough older, and exposed-canopy cockpits without masking radio.','Audio/AudioManager3D.gd:17','S16 S18 S13')
n('Aircraft interior','Airspeed rush, dirty-flight drag and stall buffet','Wired; review',2,'AirflowFeedback and ContinuousTurbulence already supply wind/rush/buffet. Check overlap and mix before adding another wind bed.','Aircraft/AirflowFeedback.gd:4; Weather/ContinuousTurbulence.gd:231','S23')
n('Aircraft interior','Canopy open/close, latch and pressure seal','Missing dedicated cues',2,'Where canopy animation exists, tie actuator, latch and wind perspective to its actual position. Skip pressure hiss for unpressurized cabins.','Aircraft scenes / cockpit controls','S49 S28')
n('Aircraft interior','Control switches, throttle detents and seat/harness movement','Missing dedicated cues',3,'Quiet local interactions with restrained variation; trigger only on actions, not every frame of axis movement.','Aircraft cockpit interaction controllers','S29')
n('Aircraft interior','Landing gear and flap operation','Partial',2,'Gear deployment/stow have recordings. Fixed-wing FlapSoundLoop assignments resolve to Resource placeholders; flap_loop.ogg has no literal hookup found. Verify and supply a real stream.','addons/simplified_flightsim/aircraft_modules/LandingGear/LandingGear.gd; Flaps/Flaps.gd','S49 S46')
n('Aircraft interior','Gear lock and touchdown confirmation','Missing dedicated cues',1,'Add physical lock clunks and wheel/suspension touchdown thumps; avoid a UI success jingle for every landing.','addons/simplified_flightsim/aircraft_modules/LandingGear/LandingGear.gd','S28 S45')
n('Aircraft interior','Critical flight/system warnings','Missing dedicated cues',1,'Separate stall/overspeed/gear unsafe/power failure meanings where those states exist. Prioritize one urgent cue, with cooldowns and acknowledgement.','HUD/instrument_panel.gd; Aircraft/RegionalDamageSystems.gd','S51')
n('Aircraft damage','Part tear-off, spar snap and skin crumple','Missing dedicated cues',1,'Layer a short fracture transient, metallic strain and loose fragments; size by damaged part and emit once per actual detachment.','Aircraft/AircraftPartDamageModel.gd:538','S37 S39 S38')
n('Aircraft damage','Control-surface or gear breakaway','Missing dedicated cues',1,'Small, sharp variants for aileron/gear versus heavy wing/tail separation. Preserve spatial location as debris separates.','Aircraft/AircraftPartDamageModel.gd:610','S37 S38 S43')
n('Aircraft damage','Motor damage, arcing and dying bearings','Missing dedicated cues',1,'Damage-driven irregular whine/grind and electrical crackle; sound follows disabled/reduced-power state and stops on destruction.','Aircraft/RegionalDamageSystems.gd; Aircraft/DamageEffects.gd','S44 S04 S47')
n('Aircraft damage','Loose panel flutter and structural stress','Missing dedicated cues',2,'Airflow-dependent rattle for a damaged section; separate from healthy stall buffet. Avoid implying imminent failure unless the state supports it.','Aircraft/AircraftPartDamageModel.gd; Aircraft/AirflowFeedback.gd','S43 S37')
n('Aircraft damage','Canopy hits and cracking','Partial',2,'Bullet metal/dirt impacts exist; dedicated glass/canopy and cockpit transmission variants would make hit location clearer.','Projectiles/ProjectileNew/projectile_new.gd:652','S39')
n('Ground contact','Normal wheel touchdown, roll and brakes','Missing dedicated cues',1,'Contact thump, rolling texture and short brake chirp with speed/surface scaling; separate from gear deployment.','Aircraft/AircraftGroundContact.gd:15; LandingGear.gd','S45 S41')
n('Ground contact','Belly slide on dirt, gravel, rock and deck','Missing dedicated cues',1,'Initial impact + sustained friction + bumps/debris + settling. Use relative contact speed and surface; fade when airborne or stopped.','Aircraft/AircraftGroundContact.gd','S35 S36 S40 S41 S42')
n('Ground contact','Wingtip/propeller ground strike and cartwheel impacts','Missing dedicated cues',1,'Distinct short strikes with contact-episode cooldown, separate from sustained fuselage scrape; broken prop must no longer sound healthy.','Aircraft/AircraftGroundContact.gd; Aircraft/RegionalDamageSystems.gd','S37 S39 S40')
n('Ground contact','Detached debris bouncing and settling','Missing dedicated cues',2,'Bounded impact pool by material and mass; only the most audible nearby collisions, then silence at rest.','Aircraft/AircraftPartDamageModel.gd:650','S38 S43')
n('Escape and rescue','Canopy jettison, ejection seat and parachute','Missing dedicated cues',1,'Staged release, seat launch, wind transition, chute opening and cloth flutter; no engine interior hum after ejection.','Aircraft/EjectionSequence.gd','S50 S23')
n('Escape and rescue','Pilot landing, walking and rescue pickup','Partial',2,'Officer metal footsteps exist. Add appropriate ground/cloth sounds and a quiet rescue/boarding confirmation where animated.','Aircraft/EjectionSequence.gd; Audio/OfficerFootsteps.gd','S41 S45')
n('Ground vehicles','Electric drivetrains by vehicle weight','Missing dedicated cues',1,'Scout, armored carrier and harvester need start/load/coast/stop identity; current turret/weapon audio does not cover locomotion.','GroundVehicle/vehicle_friendly_light.gd; GroundVehicle/vehicle_enemy_light.gd','S01 S06 S04')
n('Ground vehicles','Tires, suspension, gravel and body rattle','Missing dedicated cues',2,'Drive surface texture, corner scrub, rough-ground suspension and limited cabin rattles. Do not use carrier treads for wheeled vehicles.','GroundVehicle/ReverseDrive.gd; vehicle movement scripts','S41 S42 S43')
n('Ground vehicles','Vehicle bay loading ramp, restraint and doors','Missing dedicated cues',2,'Motorized bay opening, ramp settling and release/load locks synced to deployment and recovery.','LandCarrier/VehicleBayManager.gd','S49 S27 S28')
n('Resources and production','Harvester arm deploy, extraction and retraction','Missing dedicated cues',1,'Servo articulation, sustained extraction/pump/grind, change of load and stow latch; distinguish corium extraction from plasteel salvage.','GroundVehicle/Harvester.gd; LandCarrier/HarvesterOps.gd','S46 S48 S42')
n('Resources and production','Cargo transfer, salvage pickup and unloading','Missing dedicated cues',2,'Mechanical handling at world pickup and carrier return; a quiet receipt cue when resources actually arrive.','LandCarrier/HarvesterOps.gd; POI/ResourceField.gd','S28 S38 S46')
n('Resources and production','Replicator assembly cycle','Partial',2,'ReplicatorChamber currently loops electrical_hum_2.wav. Add start, arm/tool activity, assembly phase change, completion and shutdown.','LandCarrier/ReplicatorChamber.gd:48; LandCarrier/ReplicatorArmMotion.gd','S48 S07 S47')
n('Weapons and combat','Machine guns and cannon families','Wired; refine',2,'Multiple shot banks already exist. Review caliber distinction, near/far tails and rates; prioritize missing actions before buying more gunshots.','Weapons/Autocannon/autocannon.gd:375','')
n('Weapons and combat','Reload, weapon mechanism, dry fire and jam','Suggested extension',2,'Only use reload/jam cues for states actually represented. Mechanical recoil/feeding can complement existing shot banks.','Weapons/Autocannon/autocannon.gd; Weapons/Guns/gun_profile.gd','S29')
n('Weapons and combat','Rocket launch, bomb release and ordnance flight','Partial',2,'rocket.wav is wired. Add rack release/door action and appropriate near-pass/flight cues where supported.','Projectiles/Rocket/rocket.gd; Weapons/hardpoint.gd','S49')
n('Weapons and combat','Impacts, ricochets and incoming near misses','Partial',2,'Metal/dirt impact banks exist. Add concrete/glass distinctions and sparse bullet crack/whizz feedback for nearby threats.','Projectiles/ProjectileNew/projectile_new.gd; Effects/BulletImpactBudget.gd','S38 S39')
n('Weapons and combat','Explosions, debris tails and burning wrecks','Partial',2,'Large explosion variants exist. Add restrained sustained wreck fire/electrical failure and mass-dependent debris tails.','Projectiles/Explosion/explosion.gd; GroundVehicle/VehicleWreck.gd','S38 S44')
n('Weapons and combat','Turret rotation and end stops','Wired; expand',2,'electric_servo.ogg follows turret motion. Differentiate heavy carrier mounts and small remote mounts; avoid spurious endpoint knocks.','Audio/TurretServoAudio.gd','S04 S46')
n('Weather and world','Storm wind and sand on canopy','Wired; review',2,'Dust-front wind, twister roar and synthetic canopy ticks/rattle exist. Add deck/body grit only where exposed; keep cockpit-only grains contained.','Weather/DustFrontVisuals.gd; Weather/TwisterVisuals.gd; Weather/CanopySandAudio.gd','S21 S22')
n('Weather and world','Electrical storm strike, crack and distant thunder','Missing dedicated cues',2,'Strike-local crack, low rolling tail and distance delay tied to the visible event; actual discharge need not always sound like ordinary rain thunder.','Weather/ElectricalStorm.gd','S44')
n('Weather and world','Wind turbines, outpost machinery and ruin creaks','Missing dedicated cues',3,'Localized rotor/transformer beds at active structures; wind openings and sparse metal movement at abandoned sites.','Buildings/WindTurbine.gd; POI/World/POIWorldSite.gd','S19 S21 S43')
n('Weather and world','Subtle biome and wildlife ambience','Suggested extension',3,'Sparse fauna/insects and distant environment appropriate to the authored biome; avoid generic birds everywhere.','Wildlife; Environment','')
n('Weather and world','Corium seep and salvage-site details','Suggested extension',3,'Quiet bubbling/venting for visible corium and loose-metal sounds while interacting with salvage; optional narrative ambience.','POI/World/CoriumSeepVisual.gd; POI/ResourceField.gd','S44 S43')
n('Interface and information','Button click, order confirmation and cancellation','Wired; review',3,'Three quiet UI cues exist with throttling. Keep hover silent and retain restrained feedback.','Audio/InterfaceAudio.gd:6','')
n('Interface and information','Contact, objective, damage and resource alerts','Partial',2,'Radio and UI feedback exist; use a small consistent cue vocabulary for new actionable information, with priority/stack limits.','Radio/RadioComms.gd; UI/CarrierConsole.gd; POI/POIManager.gd','S51 S52')
n('Interface and information','Radio squelch, static and distance degradation','Wired; review',3,'Voice queues, procedural static and Radio-bus effects already exist. Preserve intelligibility; new chatter should not block urgent calls.','Radio/RadioComms.gd:793','')
n('Interface and information','Target acquired / lost / weapon ready','Suggested extension',2,'Assign distinct tones only to existing meaningful targeting transitions; no constant beeping for ordinary selection changes.','HUD/instrument_panel.gd; targeting controllers','S52')

identities=[
 ('1 · Sand Sprite','Compact, even motor whine; soft prop pulse; modest cabin vibration','S01 S08'),
 ('2 · Crusader','Lower motor body with heavier load harmonics and slower spool envelope','S06 S02 S09'),
 ('3 · Wasp','Rougher bearings/gearbox texture and conspicuous blade pulse','S03 S11'),
 ('4 · Vulture','Heavy low-frequency prop beat; a restrained separate electrical whine','S09 S10 S02'),
 ('5 · Kestrel','Clean smooth motor tone and less cabin rattle','S01 S07 S08'),
 ('6 · Razorback','Heavy loaded prop wash and mechanical roughness; current catalog says turboprop, so reconcile that wording with the requested electric direction before production','S02 S09 S11'),
 ('7 · Dagger','Higher motor harmonic emphasis and stronger high-speed airflow','S01 S02 S23'),
 ('8 · Ghost','Restrained mechanical clatter and smooth duct/airflow character; quiet does not mean silent','S07 S08 S23'),
 ('14 · Spitewing','Small bright fast-changing motor with sharper blade buzz','S03 S04 S08'),
 ('16 · Fighter-bomber','Heavier Wasp-family motor with more low body and slower changes','S03 S09 S11'),
 ('9 · Bumblebee','Heavy utility rotor pulse and cabin/airframe vibration','S12 S15'),
 ('10 · Dune Skimmer','Light rotor texture with sharper transient response','S12 S03'),
 ('11 · Hummingbird','Softer light rotor and reduced cabin rattle','S12 S13'),
 ('12 · Huntsman','Heavy coaxial interaction and load-dependent beating; do not fake identity solely by lowering pitch','S12 S15'),
 ('13 · Dragonfly','Light rotor plus more exposed wind around the bubble/open frame','S12 S23'),
 ('15 · Medium attack','Mid-weight blade rhythm, distinct from both utility and heavy attack','S12 S13 S15'),
]
